version: "3"
services:
        client:
                image: node:alpine
                restart: always
                ports:
                        - "3000:3000"
                working_dir: /client/src/app
                volumes:
                        - ./client:/client/src/app
                entrypoint: ["npm", "start"]
                networks: 
                        - webappnetwork
        
        mongo: 
                image: mongo
                restart: always
                container_name: mongodb
                volumes: 
                        - ./data-node:/data/db
                ports: 
                        - "27017:27017"
                command: mongod --noauth --smallfiles
                networks: 
                        - webappnetwork
                
networks:
        webappnetwork:
                driver: bridge
